services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment: .env
    volumes:
      - ../data/mariadb_data
    networks:
      - inception_network

  wordpress:
    build:
    environment: .env
    volumes:
      - ../data/wordpress_data
    networks:
      - inception_network

  nginx:
    build:
    ports:
      - "${NGINX_PORT}:443"
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - inception_network


# volumes:
#   mariadb_data:
#   wordpress_data:


#networks:
#  inception_network: