services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: 
      - ../.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: 
      - ../.env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports: 
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/evoronin/data/db
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/evoronin/data/wp
      o: bind

networks:
 inception_network:
  driver: bridge