services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    build:
    environment: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network

  nginx:
    build:
    ports:
      - "${NGINX_PORT}:443"
    volumes:
      - nginx_data:/etc/nginx
    networks:
      - inception_network


volumes:
  mariadb_data:
    name: mariadb_data
  wordpress_data:
    name: wordpress_data
  nginx_data:
    name: nginx_data


networks:
 inception_network: